KFRD-25 Second part of integration tests was implemented
bwsw/kafka-reader pull request #32
Opened 2017-11-24 07:31 UTC by MedvedevBW

2017-11-24 07:32 UTC, MedvedevBW commented
@placccebo

2017-11-24 09:01 UTC, placccebo requested changes

2017-11-24 09:01 UTC, placccebo commented on src/it/scala/com/bwsw/kafka/reader/KafkaReaderIntegrationTest.scala
> +  it should "process some part of events from single Kafka topic, save checkpoint data (indicating what events have been processed), " +
it should "process some part of events from single Kafka topic, save checkpoint data (indicating what events have been processed). Next, run from a scratch and repeat the two first steps for the rest of events. Then run again from a scratch and it should not receive any message"

2017-11-24 09:03 UTC, placccebo requested changes

2017-11-24 09:03 UTC, placccebo commented on src/it/scala/com/bwsw/kafka/reader/KafkaReaderIntegrationTest.scala
> +    val sizeTestDataSet = testDataSet.size
testDataSetSize

2017-11-24 10:33 UTC, MedvedevBW commented on src/it/scala/com/bwsw/kafka/reader/KafkaReaderIntegrationTest.scala
> +  it should "process some part of events from single Kafka topic, save checkpoint data (indicating what events have been processed), " +
ok

2017-11-24 10:34 UTC, MedvedevBW commented on src/it/scala/com/bwsw/kafka/reader/KafkaReaderIntegrationTest.scala
> +    val sizeTestDataSet = testDataSet.size
ok

2017-11-24 10:49 UTC, MedvedevBW commented
@placccebo

2017-11-27 02:36 UTC, placccebo approved these changes

2017-11-27 04:19 UTC, merged